services:
  app:
    build:
      dockerfile: ./Dockerfile
    working_dir: /app
    ports:
      - 3000:3000
    #volumes:
    #  - ./:/app
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yaml"
    ports:
      - 4040:4040
    volumes:
      - ./private/ngrok.yaml:/etc/ngrok.yaml